<AdminScreen>:
    name: "admin"

    MDBoxLayout:
        orientation: "vertical"
        padding: "20dp"
        spacing: "12dp"

        MDLabel:
            text: "ADMIN PANEL"
            halign: "center"
            bold: True
            font_style: "H5"

        MDButton:
            on_release: root.show_users()
            MDButtonText:
                text: "Používatelia"

        MDButton:
            on_release: root.create_user()
            MDButtonText:
                text: "➕ Nový používateľ"

        MDButton:
            on_release: root.settings()
            MDButtonText:
                text: "Nastavenia"

        MDButton:
            on_release: root.close_cycle()
            MDButtonText:
                text: "Uzavrieť kolo"

        MDButton:
            on_release: root.previous_cycle()
            MDButtonText:
                text: "Minulé kolo"

        MDButton:
            on_release: root.history()
            MDButtonText:
                text: "História"

        Widget:

        MDButton:
            on_release: root.logout()
            MDButtonText:
                text: "Odhlásiť"
