<AdminScreen>:
    name: "admin"

    MDBoxLayout:
        orientation: "vertical"
        padding: "20dp"
        spacing: "12dp"

        MDLabel:
            text: "ADMIN PANEL"
            halign: "center"
            bold: True
            font_style: "H5"

        MDButton:
            MDButtonText:
                text: "Používatelia"
            on_release: root.show_users()

        MDButton:
            MDButtonText:
                text: "➕ Nový používateľ"
            on_release: root.create_user()

        MDButton:
            MDButtonText:
                text: "Nastavenia"
            on_release: root.settings()

        MDButton:
            MDButtonText:
                text: "Uzavrieť kolo"
            on_release: root.close_cycle()

        MDButton:
            MDButtonText:
                text: "Minulé kolo"
            on_release: root.previous_cycle()

        MDButton:
            MDButtonText:
                text: "História"
            on_release: root.history()

        Widget:

        MDButton:
            MDButtonText:
                text: "Odhlásiť"
            on_release: root.logout()
