<HistoryScreen>:
    name: "history"

    MDBoxLayout:
        orientation: "vertical"
        padding: "16dp"
        spacing: "10dp"

        MDLabel:
            text: "História kôl"
            halign: "center"
            font_style: "Title"

        MDLabel:
            text: "Uzavreté kolá"
            halign: "left"

        ScrollView:

            MDList:
                id: history_list

        MDButton:
            on_release: root.back()
            MDButtonText:
                text: "Späť do Admin panela"
