#:import dp kivy.metrics.dp

<LoginScreen>

    md_bg_color: "#0F172A"

    MDBoxLayout:
        orientation: "vertical"
        padding: dp(30)
        spacing: dp(18)

        Widget:
            size_hint_y: .4

        MDLabel:
            text: "StoryFund"
            halign: "center"
            font_style: "H6"
            theme_text_color: "Custom"
            text_color: 1,1,1,1

        MDLabel:
            text: "Tvorme príbehy. Pomáhajme."
            halign: "center"
            theme_text_color: "Custom"
            text_color: .8,.85,.95,1
            size_hint_y: None
            height: dp(30)

        Widget:
            size_hint_y: .08

        MDCard:
            orientation: "vertical"
            size_hint: .92, None
            height: dp(300)
            pos_hint: {"center_x": .5}
            padding: dp(20)
            spacing: dp(15)
            radius: [24]

            MDTextField:
                id: nik
                hint_text: "NIK"

            MDTextField:
                id: pin
                hint_text: "PIN"
                password: True

            MDLabel:
                id: info
                text: ""
                halign: "center"
                theme_text_color: "Error"

            MDRaisedButton:
                text: "PRIHLÁSIŤ SA"
                pos_hint: {"center_x": .5}
                on_release: root.login()

        Widget:
            size_hint_y: .3

        MDLabel:
            text: "StoryFund v0.6"
            halign: "center"
            theme_text_color: "Hint"
            size_hint_y: None
            height: dp(30)