<NewUserScreen>:
    name: "new_user"

    MDBoxLayout:
        orientation: "vertical"
        padding: "20dp"
        spacing: "12dp"

        MDLabel:
            text: "Nový darca"
            halign: "center"
            font_style: "H5"

        MDLabel:
            text: "NIK"

        MDLabel:
            id: nik_label
            text: ""

        MDLabel:
            text: "PIN"

        MDLabel:
            id: pin_label
            text: ""

        Widget:

        MDButton:
            on_release: root.generate_new()
            MDButtonText:
                text: "Generovať znova"

        MDButton:
            on_release: root.save_user()
            MDButtonText:
                text: "Vytvoriť darcu"

        MDButton:
            on_release: root.cancel()
            MDButtonText:
                text: "Zrušiť"
