<SettingsScreen>:
    name: "settings"

    MDBoxLayout:
        orientation: "vertical"
        padding: "16dp"
        spacing: "12dp"

        MDLabel:
            text: "Nastavenia"
            halign: "center"
            font_style: "H5"
            size_hint_y: None
            height: self.texture_size[1] + dp(20)

        ScrollView:

            MDGridLayout:
                cols: 2
                adaptive_height: True
                spacing: "10dp"
                row_default_height: "48dp"
                row_force_default: True

                MDLabel:
                    text: "Testovací režim"

                MDSwitch:
                    id: test_mode

                MDLabel:
                    text: "Max. príbehov za kolo"

                MDTextField:
                    id: max_stories
                    input_filter: "int"
                    mode: "outlined"

                MDLabel:
                    text: "Počet podporených autorov"

                MDTextField:
                    id: winners_per_cycle
                    input_filter: "int"
                    mode: "outlined"

                MDLabel:
                    text: "Max. generácií"

                MDTextField:
                    id: max_generations
                    input_filter: "int"
                    mode: "outlined"

                MDLabel:
                    text: "Počet zobrazených slov"

                MDTextField:
                    id: words_to_show
                    input_filter: "int"
                    mode: "outlined"

                MDLabel:
                    text: "Počet vyberaných slov"

                MDTextField:
                    id: words_to_select
                    input_filter: "int"
                    mode: "outlined"

                MDLabel:
                    text: "Min. AI skóre"

                MDTextField:
                    id: min_ai_score
                    input_filter: "int"
                    mode: "outlined"

                MDLabel:
                    text: "Max. AI skóre"

                MDTextField:
                    id: max_ai_score
                    input_filter: "int"
                    mode: "outlined"

                MDLabel:
                    text: "Zobraziť AI skóre"

                MDSwitch:
                    id: show_ai_score

        MDBoxLayout:
            adaptive_height: True
            spacing: "10dp"

            MDButton:
                on_release: root.save_settings()
                MDButtonText:
                    text: "ULOŽIŤ"

            MDButton:
                on_release: root.back()
                MDButtonText:
                    text: "SPÄŤ"
