<UsersScreen>:
    name: "users"

    MDBoxLayout:
        orientation: "vertical"
        padding: "16dp"
        spacing: "10dp"

        MDLabel:
            text: "Darcovia"
            halign: "center"
            font_style: "H5"

        MDTextField:
            id: search_field

            MDTextFieldHintText:
                text: "Hľadať podľa NIK..."

            on_text: root.filter_users(self.text)

        MDLabel:
            id: count_label
            text: "Darcov: 0"

        ScrollView:
            MDList:
                id: users_list

        MDButton:
            on_release: root.back()
            MDButtonText:
                text: "Späť do Admin panela"
